name: Deploy Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to docs folder
        run: |
          mkdir -p docs
          rm -rf docs/*
          cp -r _build/html/* docs/

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add docs
          git commit -m "Update GitHub Pages"
          git push
